parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  node: true
  es2020: true

extends: 
  - airbnb-base

rules:
  no-console: off
  import/extensions: off
  linebreak-style: off
  no-underscore-dangle: off